# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Frontend
    url: '#frontend'
    weight: 10
  - name: Backend
    url: '#posts'
    weight: 20
  - name: Cloud Native
    url: '#talks'
    weight: 30
  - name: Language
    url: '#language'
    weight: 40
  - name: System Design
    url: '#projects'
    weight: 50
  - name: Protocol
    url: '#Protocol'
    weight: 60

  # - name: others
  #   url: '#featured'
  #   weight: 60
  
  #  Frontend
  - name: HTML
    PageRef: Frontend/HTML/_index.md
    # url: '#frontend'
    weight: 10
    parent: Frontend
  - name: CSS
    PageRef: Frontend/CSS/_index.md
    # url: '#posts'
    weight: 20
    parent: Frontend
  - name: Next.js
    PageRef: Frontend/NEXTJS/_index.md
    # url: '#posts'
    weight: 30
    parent: Frontend
  - name: React
    PageRef: Frontend/React/_index.md
    # url: '#posts'
    weight: 40
    parent: Frontend

  #  Backend
  - name: Postgres
    PageRef: Backend/Postgres/_index.md
    # url: '#posts'
    # weight: 10
    parent: Backend
  - name: Security
    PageRef: Backend/Security/_index.md
    # url: '#posts'
    # weight: 10
    parent: Backend
  # - name: Micro-Service
  #   PageRef: Frontend/HTML/abcxx.md
  #   # url: '#posts'
  #   # weight: 10
  #   parent: Backend
  # - name: xxx
  #   PageRef: Frontend/HTML/abcxx.md
  #   # url: '#posts'
  #   # weight: 10
  #   parent: Backend

  #  Clode Native
  - name: kubernetes
    PageRef: Cloud Native/kubernetes/_index.md
    # url: '#posts'
    weight: 10
    parent: Cloud Native
  - name: Istio
    PageRef: Cloud Native/Istio/_index.md
    # url: '#posts'
    weight: 20
    parent: Cloud Native

# Language
  - name: nodejs
    PageRef: Language/nodejs/_index.md
    # url: '#posts'
    weight: 10
    parent: Language
  - name: C++
    PageRef: Language/C++/_index.md
    # url: '#posts'
    weight: 20
    parent: Language
  # - name: Golang
  #   PageRef: Language/Golang/_index.md
  #   # url: '#posts'
  #   weight: 30
  #   parent: Language

# Protocol
  - name: Protocol
    PageRef: Protocol/_index.md
    url: '#Protocol'
    # weight: 10
    # parent: Language

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
